### ISSUE TITLE
Roadmap to 2.0

### ISSUE THREAD

**Issue by RobinCK** [RobinCK/typeorm-fixtures#3]
- [ ] $ref support (fixture scope)
 - [ ] config support
 - [x] configure faker locale (implemented in 1.8.0)
 - [ ] ~~optional data~~
 - [ ] reference to property
 - [ ] extend fixtures file
 - [ ] logger / debug
 - [x] integration tests
 - [x] class-transformer support
 - [x] require option for registred ts-node and other
 - [x] support tree repository
 - [x] optional ignoreDecorators [true/false] #87

**Comment by diegolaciar** [comment]
+1 Integration tests

**Comment by byCedric** [comment]
Would love to see some "helper methods" to create fixtures from tests. 😄

**Comment by thonythony** [comment]
@RobinCK is support tree repository ready (as you checked in your list) ? I need this feature, if you have already developed, can you release it please (in 2.0.0-alpha by example) ?

**Comment by RobinCK** [comment]
entity: https://github.com/RobinCK/typeorm-fixtures-sample/blob/master/entity/Category.ts
fixtures: https://github.com/RobinCK/typeorm-fixtures-sample/blob/master/fixtures/Category.yml

**Comment by aynik** [comment]
Looks like at the moment we cannot use `@references` when we define relation columns with `@RelationId()`. Is there a plan to support this?

**Comment by kop7** [comment]
+1 configure faker locale

**Comment by maximelafarie** [comment]
For those who are looking for a way to add custom localized content to database, I share with you my workaround:

Add a `processor` to your entity:

```yaml
entity: User
processor: ../processor/user.processor.ts
items:
  user{1..100}:
    produit: '@produit{1..5}'
    groupe: '@groupe{1..4}'
    bio: '{{lorem.paragraph}}'
```

In your processor, you can do the following:

```typescript
import { IProcessor } from 'typeorm-fixtures-cli';
import { User } from '../src/user/user.entity';

import * as faker from 'faker';
faker.locale = 'fr'; // <-- Whatever locale you want

export default class UserProcessor implements IProcessor<User> {

  private randomNumberBetween(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  private get nameEmail(): object {
    const nom = faker.name.lastName();
    const prenom = faker.name.firstName();
    const email = `${prenom.toLowerCase()}.${nom.toLowerCase()}@domain.io`;

    return { nom, prenom, email };
  }

  private get randomAddress(): string {
    return `${this.randomNumberBetween(1, 100)} rue ${faker.address.streetName}`;
  }

  preProcess(name: string, object: any): any {
    // Add any prop you want to customize in your fixture
    return {
      ...object,
      ...this.nameEmail,
      civilite: this.randomNumberBetween(1, 2),
      telephone: faker.phone.phoneNumber,
      adresse: this.randomAddress,
      codePostal: faker.address.zipCode,
      ville: faker.address.city,
    };
  }

  postProcess(name: string, object: { [key: string]: any }): void {
    // Do some processing after data is persisted
  }
}
```

Hope it will help you guys! 🤘
